# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-jwVVpD1XSGxe3AhcG5CJGAQg6bfqkq
"""

import pandas as pd
df = pd.read_csv('sales_data_sample.csv', encoding = 'latin1')
print("The shape of the data: ", df.shape)
print()
print("The dtypes of the data: ", df.dtypes)
print()
print("Sum of the Missing values: ", df.isnull().sum())
print()
print('Sum of the Duplicates: ', df.duplicated().sum())
print()
print(df)

#Data Cleaning

missing_cols = df.isnull().sum()
print(missing_cols)
print()
missing_cols_name = missing_cols[missing_cols > 0].index
print(missing_cols_name)
print()
df[missing_cols_name] = df[missing_cols_name].fillna('Unknown')
print('Number of missing values after the filling missing values: ', df.isnull().sum().sum())

#Orderdate to Datetime

print(df['ORDERDATE'].head(5))
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])
print(df['ORDERDATE'].dtypes)
print()
print(df['ORDERDATE'].head(5))

#Summary Statistics

print("Describe: ", df.describe().head(5))
print()
print('Value Counts: ', df['COUNTRY'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

max_ordercounts_country = df.groupby('COUNTRY')['QUANTITYORDERED'].sum().sort_values(ascending=False).head(5)
print(max_ordercounts_country)
print()

sns.barplot(x = max_ordercounts_country.index, y = max_ordercounts_country.values, color='red')
plt.title('Top 5 countries by QuantitiyOrdered')
plt.xlabel('Countries')
plt.ylabel('Quantitty Ordered')

plt.show()